default_install_hook_types:
- pre-commit
repos:
- hooks:
  - id: check-merge-conflict
    stages:
    - pre-commit
  - id: end-of-file-fixer
  - id: check-toml
    stages:
    - pre-commit
  - id: check-yaml
    stages:
    - pre-commit
  - id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
- hooks:
  - args:
    - --fix
    - --exit-non-zero-on-fix
    id: ruff-check
    stages:
    - pre-commit
  - id: ruff-format
    stages:
    - pre-commit
  repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.12.2
- hooks:
  - args:
    - -s
    - B404,B603,B310
    exclude: (_test\.py|conftest\.py)$
    id: bandit
    language_version: python3
    stages:
    - pre-commit
  repo: https://github.com/PyCQA/bandit
  rev: 1.8.5
- hooks:
  - id: detect-secrets
    stages:
    - pre-commit
  repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
- hooks:
  - id: check-undeclared
    stages:
    - pre-commit
  - id: check-unused
    stages:
    - pre-commit
  repo: https://github.com/tweag/FawltyDeps
  rev: v0.20.0
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - pre-push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v4.5.0
